# Configuracoes do servidor
server.port=8080

# Configuracoes do banco de dados SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=trabalhoPOO;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=1234

# Configuracoes JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Nome da aplicacao
spring.application.name=projeto-faculdade

# Configuracoes do MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/trabalhoPOO_logs
spring.data.mongodb.auto-index-creation=true
